ams/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from ams.accounts.forms import AMSAuthenticationForm
from ams.accounts.views import (ChangeReportingView, ChangeUserStatus, DashboardView, DocAcceptView,
                                DocRejectView, DocsView, EmployeeProfileView, EmployeesView,
                                EmployeeTerminationView, ProfileView, SetReferralView, UsersView,
                                ChangeMappingView)

opsurlpatterns = [
    path('', DashboardView.as_view(), name='homepage'),
    path('docs/', DocsView.as_view(), name='docs'),
    path('doc_accept/', DocAcceptView.as_view(), name='doc_accept'),
    path('doc_reject/', DocRejectView.as_view(), name='doc_reject'),
    re_path(
        r'profile/(?P<pk>\d+)/$', ProfileView.as_view(),
        name='user_profile'
    ),
    path('users/', UsersView.as_view(), name='users'),
    path(
        'change_reporting/', ChangeReportingView.as_view(),
        name='change_reporting'
    ),
    path(
        'change_mapping', ChangeMappingView.as_view(),
        name='ops_change_mapping'
    )
]

hrurlpatterns = [
    path('', DashboardView.as_view(), name='homepage'),
    path('employees/', EmployeesView.as_view(), name='employees'),
    re_path(
        r'employee_profile/(?P<pk>\d+)/$', EmployeeProfileView.as_view(),
        name='employee_profile'
    ),
    path(
        'terminate_employee/', EmployeeTerminationView.as_view(),
        name='terminate_employee'
    ),
    path(
        'change_reporting/', ChangeReportingView.as_view(),
        name='change_reporting'
    ),
    path(
        'change_mapping', ChangeMappingView.as_view(), name='hr_change_mapping'
    )
]

t2urlpatterns = [
    path(
        'change_mapping', ChangeMappingView.as_view(), name='t2_change_mapping'
    )
]


urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            form_class=AMSAuthenticationForm,
            template_name='accounts/login.html',
            redirect_authenticated_user=True,
        ),
        name='dash_login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='accounts/login.html',
            next_page='../'
        ),
        name='dash_logout'
    ),
    path('set_referral/', SetReferralView.as_view(), name='set_referral'),
    path('user_status/', ChangeUserStatus.as_view(), name='change_user_status'),
]

urlpatterns.extend(opsurlpatterns)
urlpatterns.extend(hrurlpatterns)

ams/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView
from django.urls import include, path, re_path

import ams.glue_registry  # noqa
from ams.accounts.forms import AMSAuthenticationForm, AMSPasswordResetForm
from ams.accounts.urls import hrurlpatterns, opsurlpatterns, t2urlpatterns
from ams.accounts.views import email_verify, frame, IndexView, profile, signUp

admin.site.site_header = 'AMS Administration'
admin.site.site_title = 'AMS Administration'
admin.site.index_title = 'AMS Administration'
admin.site.login_form = AMSAuthenticationForm

urlpatterns = [
    path('password_reset/', PasswordResetView.as_view(form_class=AMSPasswordResetForm), name='password_reset'),
    path('', include('django.contrib.auth.urls')),

    path('', IndexView.as_view(), name='index'),
    path('frame-page/', frame, name='frame'),
    path('profile', profile, name='profile'),
    path('sign-up', signUp, name='signUp'),

    path('admin/', admin.site.urls),
    path('api/', include('glue.http.urls')),
    path('accounts/', include('ams.accounts.urls')),
    path('ops/', include(opsurlpatterns)),
    path('hr/', include(hrurlpatterns)),
    path('t2/', include(t2urlpatterns)),

    re_path(
        r'^email_verification/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        email_verify,
        name='email_verification'
    ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ams/base/models.py
from django.db import models


class TimeStampModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        # Manually append `modified_at` to the field list if `update_fields`
        # argument is sent while saving the instance.
        if kwargs.get('update_fields'):
            kwargs.update({
                'update_fields': kwargs.get('update_fields').append('modified_at')
            })
        return super().save(*args, **kwargs)


class IPAddressHistoricalModel(models.Model):
    """
    Abstract model for history models tracking the IP address.
    """
    ip_address = models.GenericIPAddressField()

    class Meta:
        abstract = True

ams/data/models.py
import uuid

from django.contrib.postgres.fields.jsonb import JSONField
from django.db import models
from simple_history.models import HistoricalRecords

from ams.base.models import TimeStampModel
from ams.base.validators.form_validators import file_extension_validator
from ams.utils import timezone


def document_upload(instance, filename):
    """
    Stores the attachment in a 'per private-documents/module-type/yyyy/mm/dd' folder.
    :param instance, filename
    :returns ex: private-documents/User-DrivingLicense/2016/03/30/filename
    """
    today = timezone.get_today_start()
    return 'private-documents/{model}-{type}/{year}/{month}/{day}/{filename}.{extn}'.format(
        model=instance._meta.model_name,
        type=instance.type, year=today.year, month=today.month,
        day=today.day, filename=uuid.uuid4(), extn=filename.split('.')[-1]
    )


def file_upload(instance, filename):
    """
    Stores the attachment in a 'per private-documents/module-type/yyyy/mm/dd' folder.
    :param instance, filename
    :returns ex: private-documents/User-DrivingLicense/2016/03/30/filename
    """
    today = timezone.get_today_start()
    return 'transaction-documents/{model}/{year}/{month}/{day}/{filename}.{extn}'.format(
        model=instance._meta.model_name, year=today.year, month=today.month,
        day=today.day, filename=uuid.uuid4(), extn=filename.split('.')[-1]
    )


def upload_image(instance, image):
    """
    Stores the attachment in a 'per ams-gallery/module-type/yyyy/mm/dd' folder.
    :param instance, filename
    :returns ex: ams-gallery/User-profile/2016/03/30/filename
    """
    today = timezone.get_today_start()
    return 'ams-gallery/{model}/{year}/{month}/{day}/{pk}_{image}'.format(
        model=instance._meta.model_name,
        year=today.year, month=today.month,
        day=today.day, pk=instance.pk, image=image,
    )


class State(models.Model):
    state_name = models.CharField(max_length=128, blank=True, null=True)
    gst_code = models.CharField(max_length=2, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.state_name


class City(models.Model):
    city_name = models.CharField(max_length=128, blank=True, null=True)
    state = models.ForeignKey(State, blank=True, null=True, default=None, on_delete=models.PROTECT)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.city_name


class Address(models.Model):
    address_line1 = models.CharField(max_length=128, blank=True, null=True)
    address_line2 = models.CharField(max_length=128, blank=True, null=True)
    address_line3 = models.CharField(max_length=128, blank=True, null=True)
    city = models.ForeignKey(
        City, blank=True, null=True, default=None, on_delete=models.PROTECT
    )
    pincode = models.CharField(max_length=6, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Addresses'

    def get_full_address(self):
        address = self.address_line1
        if self.address_line2:
            address = '{} {}'.format(address, self.address_line2)
            if self.address_line3:
                address = '{} {}'.format(address, self.address_line3)
        return address


class Transaction(models.Model):
    uuid = models.UUIDField(editable=False)
    data = JSONField(blank=True, null=True)

    doc1 = models.FileField(
        validators=[file_extension_validator], upload_to=file_upload,
        blank=True, null=True, default=None
    )
    doc2 = models.FileField(
        validators=[file_extension_validator], upload_to=file_upload,
        blank=True, null=True, default=None
    )
    doc3 = models.FileField(
        validators=[file_extension_validator], upload_to=file_upload,
        blank=True, null=True, default=None
    )
    doc4 = models.FileField(
        validators=[file_extension_validator], upload_to=file_upload,
        blank=True, null=True, default=None
    )
    doc5 = models.FileField(
        validators=[file_extension_validator], upload_to=file_upload,
        blank=True, null=True, default=None
    )
    doc6 = models.FileField(
        validators=[file_extension_validator], upload_to=file_upload,
        blank=True, null=True, default=None
    )


class DocType:
    FILE = 1
    HTML = 2


class PolicyAndContract(TimeStampModel):
    DOC_TYPE_CHOICES = (
        (DocType.FILE, 'File'),
        (DocType.HTML, 'Html'),
    )
    consent_doc = models.PositiveSmallIntegerField(
        unique=True, blank=True, null=True
    )
    title = models.CharField(max_length=50, blank=True, null=True)
    short_name = models.CharField(max_length=12, blank=True, null=True)
    doc_type = models.PositiveSmallIntegerField(
        choices=DOC_TYPE_CHOICES, blank=True, null=True
    )
    file = models.FileField(
        upload_to=file_upload,
        blank=True, null=True, default=None
    )
    released_date = models.DateField()
    version = models.CharField(max_length=5)

    history = HistoricalRecords(
        history_change_reason_field=models.TextField(null=True)
    )

    def __str__(self):
        return f'{self.short_name}({self.version})'

    def save(self, *args, **kwargs):
        if self.file.name:
            self.doc_type = DocType.HTML if 'html' in self.file.name else DocType.FILE
        else:
            self.doc_type = None

        super().save(*args, **kwargs)
        if not self.consent_doc:
            self.consent_doc = self.pk
        super().save()

ams/rbac/models.py
from django.conf import settings
from django.db import models

from ams.base.models import TimeStampModel


class Role(TimeStampModel):
    title = models.CharField(max_length=64, blank=True, null=True)
    parent = models.ForeignKey('self', blank=True, null=True, default=None, on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class UserRole(TimeStampModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, default=None, on_delete=models.PROTECT)
    role = models.ForeignKey(Role, blank=True, null=True, default=None, on_delete=models.PROTECT)

    def __str__(self):
        return '{} - {}'.format(self.user, self.role)


class Permission(TimeStampModel):
    title = models.CharField(max_length=256, blank=True, null=True)
    key = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.title


class PermissionUser(TimeStampModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, default=None, on_delete=models.PROTECT)
    permission = models.ForeignKey(Permission, on_delete=models.DO_NOTHING, blank=True, null=True, default=None)

    def __str__(self):
        return '{} - {}'.format(self.user, self.permission)


class PermissionRole(TimeStampModel):
    role = models.ForeignKey(Role, blank=True, null=True, default=None, on_delete=models.PROTECT)
    permission = models.ForeignKey(Permission, on_delete=models.DO_NOTHING, blank=True, null=True, default=None)

    def __str__(self):
        return '{} - {}'.format(self.role, self.permission)

ams/subscription/models.py
from django.conf import settings
from django.db import models

from ams.base.models import TimeStampModel


class AgreementType:
    CUT_AND_PAY = 1
    FLOAT = 2


class Product(TimeStampModel):
    name = models.CharField(max_length=256, blank=True, null=True)
    product_slug = models.SlugField(max_length=64, unique=True, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Subscription(TimeStampModel):
    AGREEMENT_TYPE_CHOICES = (
        (AgreementType.CUT_AND_PAY, 'Cut and Pay'),
        (AgreementType.FLOAT, 'Float'),
    )
    subscriber = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    agreement_type = models.PositiveSmallIntegerField(choices=AGREEMENT_TYPE_CHOICES, blank=True, null=True)
    base_commission_percentage = models.FloatField(default=0.0, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Subscription'
        unique_together = ('subscriber', 'product')

ams/templates/account.html
{% extends "base.html" %}
{% load static from staticfiles %}
{%load commontags%}
{% load staticfiles %}
<head>
	<title>Sign in</title>
</head>
{% block content %}
	<style type="text/css" media="screen">
		* { outline: none !important; }
		input:-webkit-autofill {
	    	background-color: white !important;
		}
		.loginForm {width: 500px;margin: 50px auto;height: auto;min-height: 500px;padding: 25px 40px 25px;border-radius: 8px;-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
		    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
		    -webkit-transition:1s;
		}
		.forgetPassword{color: #1669b2;text-decoration: underline; cursor: pointer;text-align: right;font-weight: 600;}
		.form-group button{color: #fff;background: linear-gradient(#fc8200,#ffa11a);border-radius: 25px;border-radius: 25px;width: 155px;margin-top: 0!important;font-size: 20px;border: none !important;
		}
		.focused label { position: absolute !important;top: -5px !important; left: 0 !important; font-size: 11px !important;
		}
		.form-group{  margin: 10px 0;padding: 0;border: 0;position: relative;
	  	}
	  	.form-group input {display: block;width: 100%;height: 3em;padding: 16px 8px;border: 0;
		  	border-radius: 0;font-size: 16px;font-weight: 400;line-height: 1;background: none !important;color: #212121;outline: 0;appearance: none;transition: all 0.2s ease-in-out;border-bottom: 2px solid #ccc;
	  	}
	  	.form-group  label { position: absolute; top: 15px;left: 8px; color: #909090; transform: translate3d(0, 0, 0);transition: all 0.2s ease-in-out;
	  	}
	</style>
	<body>
		<div class="loginForm" style="display: none">
			<div class="mainLogo" style="text-align: center;"><img style="max-width: 180px;" src=""></div>
			<div class="signInWrapper">
				<div class="loginHeader" style="text-align: center;">
					<h3>Sign in</h1>
					<p>Continue to RenewBuy</p>
				</div>
				<form>
					<div class="form-group">
						<label for="email">Email address</label>
						<input type="email" class="email" id="email" autocomplete="off">
					</div>
					<div class="error"></div>
					<div class="form-group">
						<label for="pwd">Password</label>
						<input type="password" id="password" id="pwd" autocomplete="off">
					</div>
					<div class="error"></div>
					<div id="error_text"></div>
					<div class="form-group" style="text-align: right;">
						<span class="forgetPassword" onclick="resetNewPassword()" style="font-weight: 600"> Forgot password?</span>
					</div>
					<div class="form-group" style="text-align: center; margin-top: 28px;">
						<button type="button" class="btn btn-default" id="submitbutton" onclick="accountlogin()">Sign in</button>
					</div>			
				</form>
			</div>

			<div class="forgotWrap" id="forgotWrapper" style="display: none;">
				<form>
					<h5 style="text-align: center; margin-top: 30px;">Forgot your password?</h5>
					<p style="font-size: 13px;">Enter your email address below, and we'll email instructions for setting a new one.</p>
					<div class="form-group">
						<label for="email">Email address</label>
						<input type="email" class="email" id="passwordemail" autocomplete="off">
					</div>
					<div class="error"></div>
					<div class="forgetPassword" onclick="backToLogin()">Back to login </div>
					<div class="form-group" style="text-align: center; margin-top: 28px;">
						<button type="button" class="btn btn-default" id="passwordsubmit" onclick="forgotpassward()">Submit</button>
					</div>		
				</form>
			</div>
			<div class="sucessMsg" style="display: none;">
				<h4>Check your inbox.</h4>
				<p>We've emailed you instructions for setting your password. If you are registered, You should receive the email shortly!</p>
				<div class="forgetPassword" onclick="backToLogin()">Back to login </div>
			</div>	
		</div>
		<div class="loader" style="display: none">
		    <div class="fetching_profile"><i class="fa fa-spinner fa-spin"></i> <span id="load_text">Fetching Profile</span></div>
		</div>
	</body>
	<script type="text/javascript" src="{% static 'js/account.js' %}"></script>
	<script type="text/javascript">
		var requestMethod = '{{request.META.REQUEST_METHOD}}'
		var travLogo = "{% static 'images/travlogo.png' %}"
		var renewbuyLogo = "{% static 'images/renewbuy_logo.png' %}"
		const CURRENT_ENV_API_KEY  = "{% read_setting 'CURRENT_ENV_API_KEY' %}"
    	const CURRENT_ENV_SECRET_KEY  = "{% read_setting 'CURRENT_ENV_SECRET_KEY' %}"
    	const DOMAIN  = "{% read_setting 'DOMAIN' %}";
    	// authorized domains list
    	var authorizedDomains = [];
		{% for domain in allowed_domains %}
			var domain = "{{ domain }}"
			domain = domain.replace(/[^a-zA-Z/./ ]/g,'');
			authorizedDomains.push(domain);
		{% endfor %}
		
		function redirectUrl(){
			var windowUrl = window.location.href;
			var url = window.location.href.slice(window.location.href.indexOf('?') + 6).split('&');
			window.location.href = url;
		}

		$(document).on("click", "#alertBox button,body", function(){
			$('.loginForm').show();
			$('#alertBox,.modal-backdrop ').hide();
		})
		
		// post method call
		if(requestMethod == "POST"){
			{% if login_response.token %}
				localStorage.setItem('items', JSON.stringify({{login_response_json|safe}}));
				redirectUrl();
				$('.loader').show()
			{% else %}
				var errorMsg = "{{login_response.detail.error.0}}"
				if(errorMsg != ''){
					showAlertBox("{{login_response.detail.error.0}}" , "red");
				} else{
					redirectUrl();
				}
			{% endif %}
		} else{
			$('.loginForm').show();
			initialLoading();
		}
	</script>

	<script type="text/javascript" src="{% static 'js/loginWidget.js' %}"></script>
</html>
{% endblock %}

ams/templates/base.html
<!-- templates/base.html -->
{% load static from staticfiles %}
{% load commontags %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
	<link href="https://fonts.googleapis.com/css?family=Roboto:500" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/material.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
	<link rel="stylesheet" href="{% static 'scss/icons/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <script type="text/javascript" src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/utils.js' %}"></script>
   	<script type="text/javascript" src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
   	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

	{% block header %}{% endblock %}
</head>
<body>
    <main>
        <!-- Error Alert Box start -->
		    <div id="alertBox" class="modal fade" tabindex="-1" role="dialog">
		      <div class="modal-dialog">
		          <div class="modal-content">
		              <div class="modal-body text-center">
		                  <div class="container-fluid">
		                      <div class="row">
		                          <div class="col-xs-12">
		                              <h5 class="content" style="font-size: 18px;"></h5>
		                          </div>
		                      </div>
		                      <div class="row">
		                          <div class="col-md-12 text-center">
		                              <button type="button" data-dismiss="modal" style="cursor: pointer;" class="btnSubmit">Ok</button>
		                          </div>
		                      </div>
		                  </div>
		              </div>
		          </div>
		      </div>
		    </div>
    	<!-- Error Alert Box end -->
    	{% block content %} {% endblock %}
    </main>
</body>
</html>

ams/templates/posp_email.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Renewbuy POSP Agreement emailer</title>
        <meta charset="utf-8">
        <meta name="description" content="Renewbuy">
        <meta name="author" content="Renewbuy">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <style type="text/css">
            #Table_01 {
                width: 650px;
                background: #fff;
                border: 1px solid #b2b2b2;
                font-family: Arial, Helvetica, sans-serif; 
            }
            .padding-10 {
                padding: 10px;
            }
            .address-details {
                font-weight: 600;
                font-size: 11px;
                font-family: Arial, Helvetica, sans-serif;
            }
            .table_content {
                font-size: 13px;
                line-height: 20px;
                color: #000 ;
                padding: 5px 15px;
                font-family: Arial, Helvetica, sans-serif;
                font-weight: normal;
            }
            .contact-details {
                padding: 5px 15px; 
                padding-bottom: 5%; 
                font-family: Arial, Helvetica, sans-serif; 
                font-size: 14px; 
                color: #615c5c;
            }
            .disclaimer {
               font-size: 11px;
               color:#000;
               text-align: justify;
               padding: 10px 20px;
               color: #fff;
            }

        </style>
    </head>
    <body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
        <table width="650" border="0" cellspacing="0" cellpadding="0" align="center" id="Table_01">
            <tbody>
                <tr>
                <!-- renewbuy logo -->
                    <td colspan="6" align="left" valign="top" class="padding-10"><img src="https://static.renewbuy.com/pstatic/portal/images/renewbuy_logo.0b532ddf5ff2.png" alt="" style="max-width: 100%;"></td>

                    <!-- renewbuy communication address -->
                    <td colspan="6" align="right" valign="top" class="padding-10">
                        <table class="address-details">
                            <tr><td>Renewbuy.COM Plot No. 21,</td></tr>
                            <tr><td>CBIP Building 4th Floor, Sector 32,</td></tr>    
                            <tr><td>Gurugram, Haryana - 122001</td></tr>
                        </table>
                    </td> 

                    <!-- dividing line -->
                    <tr>
                        <td colspan="12" style="padding: 0px 15px;">
                            <hr style="border: 1px solid #b2b2b2;">
                            <hr style="border: 1px solid #b2b2b2; margin-top: -6px;">
                        </td>
                    </tr>
                </tr>

                <!-- center section -->
                <tr>
                    <td colspan="12" align="left" valign="top" class="table_content" style="font-weight: 700;">Dear 
                        <span style="font-weight: 700; text-transform: capitalize;">{{ user_name| title }}</span>,</b>
                    </td>
                </tr>
                
                <tr>
                    <td colspan="12" align="left" valign="top" class="table_content"> Congratulations! Your IRDAI Approved Renewbuy (D2C Insurance Broking) Certified POSP agreement is updated and attached for your reference.
                    </td>
                </tr>
                
                <tr>
                    <td colspan="12" align="left" valign="top" class="table_content">Please Note that there's no change in your existing POSP certificate and the old certificate (which was already shared with you earlier at
                        successful completion of exam) will be valid.
                    </td>
                </tr>
                
                <tr>
                    <td colspan="12" align="left" valign="top" class="table_content">We value your contribution and hoping that you are having great experience with Renewbuy!
                    </td>
                </tr>
                <!-- contact details -->
                <tr>
                    <td colspan="12" align="left" valign="top" class="contact-details">Feel free to Call 18004197151 in case of any query
                    </td>
                </tr>

                <tr>
                    <td align="left" valign="top" class="table_content">Warm Regards,</td>
                </tr>
                <tr>
                    <td align="left" valign="top" class="table_content">Team RenewBuy</td>
                </tr>

                <!-- Footer Section -->
                <tr>
                    <td colspan="12" align="left" valign="top" style="background:#FFF;">
                       <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background:#2868b0;     margin-top: 20px;">
                            <tbody>
                              <tr>
                                <td align="left" valign="top" class="disclaimer"> D2C INSURANCE BROKING PVT. LTD (CIN U66030DL2013PTC249265) Broking License No. -505, License Code - IRDA/DB/571/14, License category- Direct Broker (Life & General), valid till 26/11/2020. This message is for private circulation only</td>
                              </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>

ams/templates/upload.html
{% extends "accounts/base.html" %} {% load static from staticfiles %}
{% block page_title %}
<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="row page-titles">
    <div class="col-md-5 col-8 align-self-center">
        <h3 class="text-themecolor">Dashboard</h3>
    </div>
    <div class="col-md-7 col-4 align-self-center"> </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
{% endblock %}

{% block page_content %}
<!-- Row -->
<div class="row">
    <!-- Column -->
    <div class="col-lg-8 col-md-7">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-wrap">
                            <div>
                                <h3 class="card-title">Change Mapping</h3>
                                <h6 class="card-subtitle"></h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="table-responsive">
                            <form method="POST" class="post-form" enctype="multipart/form-data">  
						        {% csrf_token %}
                                <p><label for="id_reporting_type">Reporting type:</label>
                                    <select name="reporting_type" required="" id="id_reporting_type">
                                        <option value="" selected="">Select</option>
                                        {% for value, field in fields %}
                                            <option value="{{value}}">{{ field }}</option>
                                        {% endfor %}
                                    </select>
                                </p>
                                <p>
                                    <input type="file" name="file" required="" id="id_file">
                                </p>
						        <button type="submit" class="save btn btn-default">Submit</button>  
							</form> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}